# 00. PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [7]:
# Import torch
import torch 

# Create random tensor
random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
random_tensor_2 = torch.rand(1,7)
random_tensor_2
# Perform matrix multiplication 
matrix_multi = torch.mm(random_tensor,random_tensor_2.T)
matrix_multi

tensor([[0.4634],
        [0.9868],
        [0.7335],
        [0.7647],
        [0.6284],
        [0.2500],
        [0.9734]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(0)
A = torch.rand(7,7)
A

torch.manual_seed(0)
B = torch.rand(1,7)
B

# Matrix multiply tensors
AB = torch.matmul(A,B.T)
AB

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
import torch 
torch.cuda.is_available()

True

In [15]:
# Set random seed
random_seed = 1234

# Check for access to GPU
torch.cuda.is_available()

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device 
# Create two random tensors on GPU
torch.manual_seed(random_seed)
A = torch.rand(2,3).to(device)
B = torch.rand(2,3).to(device)
print(f'device: {device}')
A,B

device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B
tensor = torch.mm(A,B.T)
tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [22]:
# Find max
C = tensor.max()
# Find min
D = tensor.min()
C,D

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [23]:
# Find arg max
H = tensor.argmax()

# Find arg min
Y = tensor.argmin()
H,Y

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
import torch
# Set seed
random_seed = 7

# Create random tensor
torch.manual_seed(random_seed)
A = torch.rand(1,1,1,10)
# Remove single dimensions
squeezed_A = A.squeeze()

# Print out tensors and their shapes
A,A.shape , squeezed_A , squeezed_A.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))